version: "3.9"

networks:
  webapp:

services:
  web:
    image: nginx:stable-alpine
    volumes:
      - "./nginx:/etc/nginx/conf.d/"
      - "./../backend:/app"
      - "./nginx/logs:/var/logs/nginx"
    container_name: UShorterWeb
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - webapp
  php:
    image: bitnami/php-fpm:8.1
    container_name: UShorterApp
    hostname: ushorter.loc
    volumes:
      - "./../backend:/app"
    working_dir: "/app"
    depends_on:
      - mysql
    networks:
      - webapp
  mysql:
    image: mysql:5.7
    container_name: UShorterDB
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: urlshorter
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: dev
    volumes:
      - "./data/mysql:/var/lib/mysql"
    ports:
      - "3307:3306"
    networks:
      - webapp

